name = "tg-image-hosting"
main = "build/worker/shim.mjs"
compatibility_date = "2023-03-22"

[build]
command = "worker-build --release"

[vars]
TELEGRAM_TOKEN = "12324324:dsadlzcxjzldk;skx;zC"
MAINTAINER_ID = "23430109213"                                       # send random word to the chat id when cron job run

[observability.logs]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "my-d1-database"
database_id = "00000000-0000-0000-0000-000000000000"

[placement]
mode = "smart"
